package com.example.datagreenmovil.Entidades;

public enum Status {

    OK,
    ERROR,
    SIN_BASE_SQLITE,
    CONFIGURACION_LOCAL_NO_EXISTE,
    EQUIPO_NO_REGISTRADO,
    SIN_CONEXION_PRINCIPAL,
    TIEMPO_DESFASADO,
    ACTUALIZACION_SOFTWARE_DISPONIBLE,
    ACTUALIZACION_BD_DISPONIBLE,
    ACTUALIZACION_DATA_DISPONIBLE,
    TABLAS_LOCALES_NO_EXISTEN,
    DATA_LOCAL_NO_EXISTE,
    EQUIPO_HABILITADO,
    EQUIPO_NO_HABILITADO,


}
